"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type GameLanguage = "es" | "de" | "pl" | "ru" | "pt" | "la";
export type PastelTheme = "pink" | "blue" | "yellow" | "green" | "violet" | "orange" | "mint" | "coral" | "lavender" | "gray";
export type ThemeMode = "light" | "dark";

export const themeNames: Record<GameLanguage, Record<PastelTheme, string>> = {
    es: {
        pink: "Rosa",
        blue: "Azul",
        yellow: "Amarillo",
        green: "Verde",
        violet: "Violeta",
        orange: "Naranja",
        mint: "Menta",
        coral: "Coral",
        lavender: "Lavanda",
        gray: "Gris",
    },
    de: {
        pink: "Rosa",
        blue: "Blau",
        yellow: "Gelb",
        green: "Grün",
        violet: "Violett",
        orange: "Orange",
        mint: "Minze",
        coral: "Koralle",
        lavender: "Lavendel",
        gray: "Grau",
    },
    pl: {
        pink: "Różowy",
        blue: "Niebieski",
        yellow: "Żółty",
        green: "Zielony",
        violet: "Fioletowy",
        orange: "Pomarańczowy",
        mint: "Miętowy",
        coral: "Koralowy",
        lavender: "Lawendowy",
        gray: "Szary",
    },
    ru: {
        pink: "Розовый",
        blue: "Синий",
        yellow: "Жёлтый",
        green: "Зелёный",
        violet: "Фиолетовый",
        orange: "Оранжевый",
        mint: "Мятный",
        coral: "Коралловый",
        lavender: "Лавандовый",
        gray: "Серый",
    },
    pt: {
        pink: "Rosa",
        blue: "Azul",
        yellow: "Amarelo",
        green: "Verde",
        violet: "Violeta",
        orange: "Laranja",
        mint: "Menta",
        coral: "Coral",
        lavender: "Lavanda",
        gray: "Cinzento",
    },
    la: {
        pink: "Roseus",
        blue: "Caeruleus",
        yellow: "Luteus",
        green: "Viridis",
        violet: "Violaceus",
        orange: "Aurantius",
        mint: "Mentheus",
        coral: "Corallinus",
        lavender: "Lavandulaceus",
        gray: "Canus",
    },
};

export const commonTranslations = {
    es: {
        home: "Inicio",
        searchPlaceholder: "Buscar por nombre, categoría o descripción...",
        categoryAll: "Todos",
        categoryPuzzle: "Rompecabezas",
        categoryWord: "Palabras",
        categoryMemory: "Memoria",
        categoryStrategy: "Estrategia",
        categoryLogic: "Lógica",
        categoryColor: "Color",
        playNow: "Jugar",
        comingSoon: "Próximamente",
        titleLauncher: "Juegitos",
        subtitleLauncher: "Una colección chula y moderna de minijuegos. ¡Elige tu favorito!",
        noGamesFound: "No se encontraron juegos que coincidan con la búsqueda.",
        themeLabel: "Tema",
        langLabel: "Idioma",
        hechoCon: "Hecho con 🌸 y 😝",
    },
    de: {
        home: "Startseite",
        searchPlaceholder: "Suche nach Name, Kategorie oder Beschreibung...",
        categoryAll: "Alle",
        categoryPuzzle: "Puzzle",
        categoryWord: "Wortspiele",
        categoryMemory: "Gedächtnis",
        categoryStrategy: "Strategie",
        categoryLogic: "Logik",
        categoryColor: "Farben",
        playNow: "Spielen",
        comingSoon: "Demnächst",
        titleLauncher: "Juegitos",
        subtitleLauncher: "Eine charmante und moderne Sammlung von Minispielen. Wähle deinen Favoriten!",
        noGamesFound: "Keine Spiele gefunden, die der Suche entsprechen.",
        themeLabel: "Thema",
        langLabel: "Sprache",
        hechoCon: "Gemacht mit 🌸 und 😝",

    },
    pl: {
        home: "Główna",
        searchPlaceholder: "Szukaj według nazwy, kategorii lub opisu...",
        categoryAll: "Wszystkie",
        categoryPuzzle: "Puzzle",
        categoryWord: "Słowne",
        categoryMemory: "Pamięciowe",
        categoryStrategy: "Strategiczne",
        categoryLogic: "Logiczne",
        categoryColor: "Kolory",
        playNow: "Graj",
        comingSoon: "Wkrótce",
        titleLauncher: "Juegitos",
        subtitleLauncher: "Urocza i nowoczesna kolekcja minigier. Wybierz swoją ulubioną!",
        noGamesFound: "Nie znaleziono gier pasujących do wyszukiwania.",
        themeLabel: "Motyw",
        langLabel: "Język",
        hechoCon: "Stworzone z 🌸 i 😝",

    },
    ru: {
        home: "Главная",
        searchPlaceholder: "Поиск по названию, категории или описанию...",
        categoryAll: "Все",
        categoryPuzzle: "Головоломки",
        categoryWord: "Слова",
        categoryMemory: "Память",
        categoryStrategy: "Стратегии",
        categoryLogic: "Логика",
        categoryColor: "Цвета",
        playNow: "Играть",
        comingSoon: "Скоро",
        titleLauncher: "Juegitos",
        subtitleLauncher: "Милая и современная коллекция мини-игры. Выберите любимую!",
        noGamesFound: "Игры, соответствующие запросу, не найдены.",
        themeLabel: "Тема",
        langLabel: "Язык",
        hechoCon: "Сделано с 🌸 и 😝",

    },
    pt: {
        home: "Início",
        searchPlaceholder: "Buscar por nome, categoria o descripción...",
        categoryAll: "Todos",
        categoryPuzzle: "Quebra-cabeça",
        categoryWord: "Palavras",
        categoryMemory: "Memória",
        categoryStrategy: "Estratégia",
        categoryLogic: "Lógica",
        categoryColor: "Cor",
        playNow: "Jogar",
        comingSoon: "Em breve",
        titleLauncher: "Juegitos",
        subtitleLauncher: "Uma coleção charmosa e moderna de minijogos. Escolha o seu favorito!",
        noGamesFound: "Nenhum jogo encontrado que corresponda à pesquisa.",
        themeLabel: "Tema",
        langLabel: "Idioma",
        hechoCon: "Feito com 🌸 e 😝",

    },
    la: {
        home: "Initium",
        searchPlaceholder: "Quaere per nomen, classem vel descriptionem...",
        categoryAll: "Omnia",
        categoryPuzzle: "Aenigmata",
        categoryWord: "Verba",
        categoryMemory: "Memoria",
        categoryStrategy: "Consilia",
        categoryLogic: "Logica",
        categoryColor: "Colores",
        playNow: "Ludere",
        comingSoon: "Mox futurum",
        titleLauncher: "Ludula",
        subtitleLauncher: "Collectio venusta et moderna parvorum ludorum. Elige dilectum tuum!",
        noGamesFound: "Nulli ludi inventi sunt qui investigationi conveniunt.",
        themeLabel: "Thema",
        langLabel: "Lingua",
        hechoCon: "Factum cum 🌸 et 😝",

    }
};

export const hexleTranslations = {
    es: {
        titleEagleEye: "Hexle • Ojo de Águila",
        titleClassic: "Hexle • Clásico",
        subtitleEagleEye: "Mira el color objetivo de arriba e intenta recrear su código hexadecimal en 5 intentos.",
        subtitleClassic: "El color objetivo está oculto. Usa las flechas de precisión para adivinar el código en 6 intentos.",
        modeLabelEagleEye: "Modo Ojo de Águila",
        modeLabelClassic: "Modo Clásico",
        howToPlay: "Cómo jugar",
        newColor: "Nuevo Color",
        backToHome: "Volver al inicio",
        attemptsLeft: (left: number) => `Te quedan ${left} intentos`,
        attemptsSingle: "Te queda 1 intento",
        winTitle: "¡Ganaste! 🎉",
        winDesc: (attempts: number) => `Has replicado el color secreto en ${attempts} ${attempts === 1 ? "intento" : "intentos"}.`,
        loseTitle: "¡Fin del juego! 🌸",
        loseDesc: "No has logrado adivinar el color esta vez.",
        secretColorWas: "El color secreto era:",
        helpTitle: "Cómo jugar a Hexle",
        helpIntro: "Adivina el código hexadecimal de 6 caracteres del color propuesto en 5 (Ojo de Águila) o 6 (Clásico) intentos.",
        helpRGB: "Los códigos hexadecimales representan colores usando 3 canales: Rojo (primeros 2 caracteres), Verde (los 2 del medio) y Azul (los últimos 2 caracteres). Los caracteres válidos van de 0 a 9 y de A a F.",
        helpArrows: "Bajo cada casilla se muestra una flecha de proximidad que indica hacia dónde ajustar cada dígito (de menor a mayor: 0-9, A-F):",
        helpArrowDoubleUp: "El dígito correcto es MUCHO mayor (diferencia > 2).",
        helpArrowSingleUp: "El dígito correcto es un poco mayor (diferencia de 1 o 2).",
        helpArrowSingleDown: "El dígito correcto es un poco menor (diferencia de 1 o 2).",
        helpArrowDoubleDown: "El dígito correcto es MUCHO menor (diferencia > 2).",
        helpArrowCheck: "El dígito es correcto (coincidencia exacta).",
        helpFooter: "Usa el bloque de color al final de cada fila para ver qué color estás introduciendo. ¡A practicar!",
        playAgain: "Jugar de nuevo",
        share: "Compartir resultado",
        copied: "¡Copiado al portapapeles!",
        placeholderGuess: "Escribe 6 caracteres hex...",
        targetColorLabel: "Objetivo",
        latestGuessLabel: "Último Intento",
        reset: "Reiniciar",
        stats: "Estadísticas",
        statsPlayed: "Jugadas",
        statsWon: "Ganadas",
        statsWinRate: "% Victorias",
        statsCurrentStreak: "Racha Actual",
        statsMaxStreak: "Racha Máxima",
        statsDistribution: "Distribución de Intentos",
        statsFunTitle: "Patrones y Curiosidades",
        statsModeAll: "Global",
        statsModeEagle: "Ojo de Águila",
        statsModeClassic: "Clásico",
        statsPersonality: "Personalidad",
        statsFavTime: "Hora de Juego",
        statsPerfectWins: "Victorias Perfectas (1 intento)",
        statsLastChanceWins: "Al límite (último intento)",
        statsAvgGuesses: "Promedio Intentos",
        statsTendency: "Tendencia de Ajuste",
        statsTendencyOptimist: "Optimista (apunta alto)",
        statsTendencyPessimist: "Conservador (se queda corto)",
        statsTendencyBalanced: "Equilibrado y Preciso",
        timeNight: "Búho Nocturno",
        timeMorning: "Madrugador",
        timeAfternoon: "Tarde de Café",
        timeEvening: "Relax Vespertino",
        statsNoData: "Juega una partida para ver tus estadísticas.",
        statsResetBtn: "Restablecer",
        statsResetConfirm: "Estás segura/o de que quieres borrar TODAS tus estadísticas?",
    },
    de: {
        titleEagleEye: "Hexle • Adlerauge",
        titleClassic: "Hexle • Klassisch",
        subtitleEagleEye: "Betrachte die Zielfarbe oben und versuche, ihren Hex-Code in 5 Versuchen nachzubilden.",
        subtitleClassic: "Die Zielfarbe ist versteckt. Nutze die Präzisionspfeile, um den Code in 6 Versuchen zu erraten.",
        modeLabelEagleEye: "Adlerauge-Modus",
        modeLabelClassic: "Klassischer Modus",
        howToPlay: "Wie man spielt",
        newColor: "Neue Farbe",
        backToHome: "Zurück zur Hauptseite",
        attemptsLeft: (left: number) => `Noch ${left} Versuche`,
        attemptsSingle: "Noch 1 Versuch",
        winTitle: "Gewonnen! 🎉",
        winDesc: (attempts: number) =>
            `Du hast die geheime Farbe in ${attempts} ${attempts === 1 ? "Versuch" : "Versuchen"} nachgebildet.`,
        loseTitle: "Spiel vorbei! 🌸",
        loseDesc: "Du hast die Farbe dieses Mal nicht erraten.",
        secretColorWas: "Die geheime Farbe war:",
        helpTitle: "Wie man Hexle spielt",
        helpIntro: "Errate den 6-stelligen Hex-Code der gesuchten Farbe in 5 (Adlerauge) oder 6 (Klassisch) Versuchen.",
        helpRGB: "Hexadezimalcodes bestehen aus 3 Kanälen: Rot (erste 2 Stellen), Grün (mittlere 2) und Blau (letzte 2). Gültige Zeichen sind 0-9 und A-F.",
        helpArrows: "Die Pfeile unter jeder Kachel zeigen an, wie du die Ziffer anpassen musst (von niedrig nach hoch: 0-9, A-F):",
        helpArrowDoubleUp: "Die gesuchte Ziffer ist viel größer (Differenz > 2).",
        helpArrowSingleUp: "Die gesuchte Ziffer ist etwas größer (Differenz 1 oder 2).",
        helpArrowSingleDown: "Die gesuchte Ziffer ist etwas kleiner (Differenz 1 oder 2).",
        helpArrowDoubleDown: "Die gesuchte Ziffer ist viel kleiner (Differenz > 2).",
        helpArrowCheck: "Die Ziffer ist korrekt (exakte Übereinstimmung).",
        helpFooter: "Nutze das Farbfeld am Ende jeder Zeile, um deine Schätzung visuell zu überprüfen. Viel Glück!",
        playAgain: "Nochmal spielen",
        share: "Ergebnis teilen",
        copied: "In Zwischenablage kopiert!",
        placeholderGuess: "6 Hex-Zeichen eingeben...",
        targetColorLabel: "Ziel",
        latestGuessLabel: "Letzter Tipp",
        reset: "Zurücksetzen",
        stats: "Statistiken",
        statsPlayed: "Gespielt",
        statsWon: "Gewonnen",
        statsWinRate: "Gewinnrate (%)",
        statsCurrentStreak: "Aktuelle Serie",
        statsMaxStreak: "Längste Serie",
        statsDistribution: "Verteilung der Versuche",
        statsFunTitle: "Muster und Kuriositäten",
        statsModeAll: "Global",
        statsModeEagle: "Adlerauge",
        statsModeClassic: "Klassisch",
        statsPersonality: "Persönlichkeit",
        statsFavTime: "Spielzeit",
        statsPerfectWins: "Perfekte Runden (1 Versuch)",
        statsLastChanceWins: "Auf den letzten Drücker (letzter Versuch)",
        statsAvgGuesses: "Durchschnittliche Versuche",
        statsTendency: "Anpassungstendenz",
        statsTendencyOptimist: "Optimist (setzt zu hoch an)",
        statsTendencyPessimist: "Vorsichtig (bleibt darunter)",
        statsTendencyBalanced: "Ausgewogen und präzise",
        timeNight: "Nachteule",
        timeMorning: "Frühaufsteher",
        timeAfternoon: "Nachmittagsmensch",
        timeEvening: "Entspannter Abend",
        statsNoData: "Spiele eine Runde, um deine Statistiken zu sehen.",
        statsResetBtn: "Zurücksetzen",
        statsResetConfirm: "Bist du sicher, dass du ALLE deine Statistiken löschen möchtest?",
    },
    pl: {
        titleEagleEye: "Hexle • Sokole oko",
        titleClassic: "Hexle • Klasyczny",
        subtitleEagleEye: "Spójrz na kolor docelowy powyżej i spróbuj odtworzyć jego kod szesnastkowy w 5 próbach.",
        subtitleClassic: "Kolor docelowy jest ukryty. Użyj strzałek precyzyjnych, aby odgadnąć kod w 6 próbach.",
        modeLabelEagleEye: "Tryb „Sokole Oko”",
        modeLabelClassic: "Tryb Klasyczny",
        howToPlay: "Zasady gry",
        newColor: "Nowy Kolor",
        backToHome: "Powrót do strony głównej",
        attemptsLeft: (left: number) => `Pozostało ${left} prób`,
        attemptsSingle: "Pozostała 1 próba",
        winTitle: "Wygrałeś! 🎉",
        winDesc: (attempts: number) => `Odtworzyłeś sekretny kolor w ${attempts} ${attempts === 1 ? "próbie" : "próbach"}.`,
        loseTitle: "Koniec gry! 🌸",
        loseDesc: "Tym razem nie udało się odgadnąć koloru.",
        secretColorWas: "Sekretny kolor to:",
        helpTitle: "Zasady gry Hexle",
        helpIntro: "Odgadnij 6-znakowy kod szesnastkowy koloru w 5 (Sokole oko) lub 6 (Klasyczny) próbach.",
        helpRGB: "Kody szesnastkowe reprezentują kolory za pomocą 3 kanałów: Czerwony (pierwsze 2 znaki), Zielony (2 środkowe) i Niebieski (2 ostatnie). Prawidłowe znaki to 0-9 i A-F.",
        helpArrows: "Strzałka odległości pod każdym kafelkiem wskazuje kierunek dopasowania cyfry (w kolejności 0-9, A-F):",
        helpArrowDoubleUp: "Docelowa cyfra jest znacznie wyższa (różnica > 2).",
        helpArrowSingleUp: "Docelowa cyfra jest nieco wyższa (różnica 1 lub 2).",
        helpArrowSingleDown: "Docelowa cyfra jest nieco niższa (różnica 1 lub 2).",
        helpArrowDoubleDown: "Docelowa cyfra jest znacznie wyższa (różnica > 2).",
        helpArrowCheck: "Cyfra jest prawidłowa (dokładne dopasowanie).",
        helpFooter: "Użyj kolorowego pola na końcu każdego rzędu, aby zobaczyć odcień, który wpisałaś/eś. Powodzenia!",
        playAgain: "Zagraj ponownie",
        share: "Udostępnij wynik",
        copied: "Skopiowano do schowka!",
        placeholderGuess: "Wpisz 6 znaków hex...",
        targetColorLabel: "Cel",
        latestGuessLabel: "Ostatni Strzał",
        reset: "Resetuj",
        stats: "Statystyki",
        statsPlayed: "Rozegrane",
        statsWon: "Wygrane",
        statsWinRate: "% Wygranych",
        statsCurrentStreak: "Aktualna Seria",
        statsMaxStreak: "Najdłuższa Seria",
        statsDistribution: "Rozkład Prób",
        statsFunTitle: "Wzorce i Ciekawostki",
        statsModeAll: "Ogółem",
        statsModeEagle: "Sokole Oko",
        statsModeClassic: "Klasyczny",
        statsPersonality: "Osobowość",
        statsFavTime: "Pora Gry",
        statsPerfectWins: "Perfekcyjne Wygrane (w 1 próbie)",
        statsLastChanceWins: "Rzutem na Taśmę (w ostatniej próbie)",
        statsAvgGuesses: "Średnia Liczba Prób",
        statsTendency: "Tendencja Zgadywania",
        statsTendencyOptimist: "Optymista (celuje za wysoko)",
        statsTendencyPessimist: "Ostrożny (celuje za nisko)",
        statsTendencyBalanced: "Zrównoważony i Precyzyjny",
        timeNight: "Nocny Marek",
        timeMorning: "Ranny Ptaszek",
        timeAfternoon: "Popołudniowa Kawka",
        timeEvening: "Wieczorny Relaks",
        statsNoData: "Zagraj partię, aby zobaczyć swoje statystyki.",
        statsResetBtn: "Resetuj",
        statsResetConfirm: "Czy na pewno chcesz usunąć WSZYSTKIE swoje statystyki?",
    },
    ru: {
        titleEagleEye: "Hexle • Орлиный Глаз",
        titleClassic: "Hexle • Классика",
        subtitleEagleEye: "Посмотрите на целевой цвет вверху и попытайтесь воссоздать его код за 5 попыток.",
        subtitleClassic: "Целевой цвет скрыт. Используйте стрелки подсказок, чтобы угадать код за 6 попыток.",
        modeLabelEagleEye: "Режим Орлиный глаз",
        modeLabelClassic: "Режим Классический",
        howToPlay: "Как играть",
        newColor: "Новый цвет",
        backToHome: "На главную",
        attemptsLeft: (left: number) => `Осталось попыток: ${left}`,
        attemptsSingle: "Осталась 1 попытка",
        winTitle: "Победа! 🎉",
        winDesc: (attempts: number) => `Вы воссоздали цвет за ${attempts} ${attempts === 1 ? "попытку" : "попыток(-ки)"}.`,
        loseTitle: "Игра окончена! 🌸",
        loseDesc: "В этот раз не удалось угадать цвет.",
        secretColorWas: "Секретный цвет:",
        helpTitle: "Правила Hexle",
        helpIntro: "Угадайте 6-значный шестнадцатеричный код целевого цвета за 5 (Орлиный глаз) или 6 (Классический) попыток.",
        helpRGB: "Цвета кодируются тремя каналами: Красный (первые 2 символа), Зелёный (средние 2) и Синий (последние 2). Используются символы от 0 до 9 и от A до F.",
        helpArrows: "Стрелки под ячейками показывают, в какую сторону изменить символ (по порядку: 0-9, A-F):",
        helpArrowDoubleUp: "Целевой символ намного больше (разница > 2).",
        helpArrowSingleUp: "Целевой символ немного больше (разница 1-2).",
        helpArrowSingleDown: "Целевой символ немного меньше (разница 1-2).",
        helpArrowDoubleDown: "Целевой символ намного меньше (разница > 2).",
        helpArrowCheck: "Символ совпал (точное совпадение).",
        helpFooter: "Используйте цветной блок в конце строки для сравнения своего оттенка. Удачи!",
        playAgain: "Играть снова",
        share: "Поделиться",
        copied: "Скопировано в буфер!",
        placeholderGuess: "Введите 6 символов...",
        targetColorLabel: "Цель",
        latestGuessLabel: "Попытка",
        reset: "Сброс",
        stats: "Статистика",
        statsPlayed: "Сыграно",
        statsWon: "Побед",
        statsWinRate: "% Побед",
        statsCurrentStreak: "Текущая серия",
        statsMaxStreak: "Лучшая серия",
        statsDistribution: "Распределение попыток",
        statsFunTitle: "Закономерности и любопытные факты",
        statsModeAll: "Общий",
        statsModeEagle: "Орлиный глаз",
        statsModeClassic: "Классический",
        statsPersonality: "Стиль игры",
        statsFavTime: "Время игры",
        statsPerfectWins: "Идеальные победы (1 попытка)",
        statsLastChanceWins: "На грани (последняя попытка)",
        statsAvgGuesses: "Среднее число попыток",
        statsTendency: "Тенденция угадывания",
        statsTendencyOptimist: "Оптимист (берёт выше)",
        statsTendencyPessimist: "Осторожный (берёт ниже)",
        statsTendencyBalanced: "Сбалансированный и точный",
        timeNight: "Ночная сова",
        timeMorning: "Жаворонок",
        timeAfternoon: "Кофейный полдень",
        timeEvening: "Вечерний отдых",
        statsNoData: "Сыграйте партию, чтобы увидеть свою статистику.",
        statsResetBtn: "Сбросить",
        statsResetConfirm: "Вы уверены, что хотите удалить всю свою статистику?",
    },
    pt: {
        titleEagleEye: "Hexle • Olho de Águia",
        titleClassic: "Hexle • Clássico",
        subtitleEagleEye: "Observa a cor alvo acima e tenta recriar o seu código hexadecimal em 5 tentativas.",
        subtitleClassic: "A cor alvo está oculta. Usa as setas de precisão para adivinhar o código em 6 tentativas.",
        modeLabelEagleEye: "Modo Olho de Águia",
        modeLabelClassic: "Modo Clássico",
        howToPlay: "Como jogar",
        newColor: "Nova Cor",
        backToHome: "Voltar ao início",
        attemptsLeft: (left: number) => `Restam ${left} tentativas`,
        attemptsSingle: "Resta 1 tentativa",
        winTitle: "Ganhaste! 🎉",
        winDesc: (attempts: number) => `Recriaste a cor secreta em ${attempts} ${attempts === 1 ? "tentativa" : "tentativas"}.`,
        loseTitle: "Fim de jogo! 🌸",
        loseDesc: "Não conseguiste adivinhar a cor desta vez.",
        secretColorWas: "A cor secreta era:",
        helpTitle: "Como jogar Hexle",
        helpIntro: "Adivinha o código hexadecimal de 6 caracteres da cor proposta em 5 (Olho de Águia) ou 6 (Clássico) tentativas.",
        helpRGB: "Os códigos hexadecimais representam cores com 3 canais: Vermelho (primeiros 2 caracteres), Verde (2 do meio) e Azul (últimos 2). Caracteres válidos: 0-9 e A-F.",
        helpArrows: "As setas por baixo das quadrículas indicam para onde ajustar cada dígito (na ordem: 0-9, A-F):",
        helpArrowDoubleUp: "O dígito correto é MUITO maior (diferença > 2).",
        helpArrowSingleUp: "O dígito correto es um poco maior (diferença de 1 ou 2).",
        helpArrowSingleDown: "O dígito correto es um poco menor (diferença de 1 ou 2).",
        helpArrowDoubleDown: "O dígito correto é muito menor (diferença > 2).",
        helpArrowCheck: "O dígito está correto (exato).",
        helpFooter: "Usa o bloco de cor no final de cada linha para veres a cor que estás a introduzir. Boa sorte!",
        playAgain: "Jogar novamente",
        share: "Partilhar resultado",
        copied: "Copiado para a área de transferência!",
        placeholderGuess: "Escreve 6 caracteres hex...",
        targetColorLabel: "Alvo",
        latestGuessLabel: "Último Intento",
        reset: "Reiniciar",
        stats: "Estatísticas",
        statsPlayed: "Jogadas",
        statsWon: "Vitórias",
        statsWinRate: "% Vitórias",
        statsCurrentStreak: "Sequência atual",
        statsMaxStreak: "Sequência máxima",
        statsDistribution: "Distribuição de tentativas",
        statsFunTitle: "Padrões e curiosidades",
        statsModeAll: "Global",
        statsModeEagle: "Olho de Águia",
        statsModeClassic: "Clássico",
        statsPersonality: "Personalidade",
        statsFavTime: "Hora de jogo",
        statsPerfectWins: "Vitórias perfeitas (1 tentativa)",
        statsLastChanceWins: "No limite (última tentativa)",
        statsAvgGuesses: "Média de tentativas",
        statsTendency: "Tendência de ajuste",
        statsTendencyOptimist: "Otimista (aponta alto)",
        statsTendencyPessimist: "Conservador (fica aquém)",
        statsTendencyBalanced: "Equilibrado e preciso",
        timeNight: "Coruja noturna",
        timeMorning: "Madrugador",
        timeAfternoon: "Tarde de café",
        timeEvening: "Relax vespertino",
        statsNoData: "Joga uma partida para veres as tuas estatísticas.",
        statsResetBtn: "Reiniciar",
        statsResetConfirm: "Tens a certeza de que queres apagar TODAS as tuas estatísticas?",
    },
    la: {
        titleEagleEye: "Hexle • Oculus Aquilae",
        titleClassic: "Hexle • Modus Classicus",
        subtitleEagleEye: "Meta coloris supra monstratur. Recrea codicem eius intra V conatus.",
        subtitleClassic: "Meta coloris celatur. Divina codicem eius intra VI conatus per sagittas.",
        modeLabelEagleEye: "Modus Oculus Aquilae",
        modeLabelClassic: "Modus Classicus",
        howToPlay: "Regulae ludi",
        newColor: "Novus Color",
        backToHome: "Redire ad initium",
        attemptsLeft: (left: number) => `Tibi supersunt ${left} conatus`,
        attemptsSingle: "Tibi superest I conatus",
        winTitle: "Vicisti! 🎉",
        winDesc: (attempts: number) => `Colorem arcanum redegisti intra ${attempts} ${attempts === 1 ? "conatum" : "conatus"}.`,
        loseTitle: "Finis ludi! 🌸",
        loseDesc: "Hoc tempore colorem non divinasti.",
        secretColorWas: "Color arcanus erat:",
        helpTitle: "Quomodo Hexle ludatur",
        helpIntro: "Divina codicem hexadecimalem sex signorum coloris propositi intra V (Oculus Aquilae) aut VI (Classicus) conatus.",
        helpRGB: "Codices hexadecimales colores indicant per canales tres: Rubrum (duo prima signa), Viridem (duo media) et Caeruleum (duo ultima). Signa licita sunt 0-9 et A-F.",
        helpArrows: "Sagittae sub capsulis monstrant quo modo signum corrigas (in ordine: 0-9, A-F):",
        helpArrowDoubleUp: "Signum verum est MULTUM maius (differentia > 2).",
        helpArrowSingleUp: "Signum verum est PAULO maius (differentia 1 aut 2).",
        helpArrowSingleDown: "Signum verum est PAULO minus (differentia 1 aut 2).",
        helpArrowDoubleDown: "Signum verum est MULTUM minus (differentia > 2).",
        helpArrowCheck: "Signum est rectum (prorsus convenit).",
        helpFooter: "Utere capsa coloris in fine ordinis ad colorem tuum inspiciendum. Bonam fortunam!",
        playAgain: "Iterum ludere",
        share: "Partiri eventum",
        copied: "Copiatum est in scriniolum!",
        placeholderGuess: "Scribe VI signa hex...",
        targetColorLabel: "Meta",
        latestGuessLabel: "Novissimus Conatus",
        reset: "Renovare",
        stats: "Statisticae",
        statsPlayed: "Partitae",
        statsWon: "Victoriae",
        statsWinRate: "% Victoriae",
        statsCurrentStreak: "Series praesens",
        statsMaxStreak: "Series maxima",
        statsDistribution: "Distributio conatuum",
        statsFunTitle: "Exempla et curiositates",
        statsModeAll: "Universalis",
        statsModeEagle: "Oculus Aquilae",
        statsModeClassic: "Classicus",
        statsPersonality: "Personalitas",
        statsFavTime: "Hora ludi",
        statsPerfectWins: "Victoriae perfectae (uno conatu)",
        statsLastChanceWins: "In limite (ultimo conatu)",
        statsAvgGuesses: "Medius conatuum",
        statsTendency: "Tendencia aptationis",
        statsTendencyOptimist: "Optimista (alte tendens)",
        statsTendencyPessimist: "Conservator (infra tendens)",
        statsTendencyBalanced: "Aequilibratus et accuratus",
        timeNight: "Noctua nocturna",
        timeMorning: "Matutinus",
        timeAfternoon: "Postmeridies capuli",
        timeEvening: "Relax vespertinus",
        statsNoData: "Lude unam partitam ut statisticas tuas videas.",
        statsResetBtn: "Reponere",
        statsResetConfirm: "Certus es te velle OMNES statisticas tuas delere?",
    },
};

export type CentralTranslationsType = {
    common: typeof commonTranslations;
    hexle: typeof hexleTranslations;
};

export const allTranslations = {
    es: {
        common: commonTranslations.es,
        hexle: hexleTranslations.es,
    },
    de: {
        common: commonTranslations.de,
        hexle: hexleTranslations.de,
    },
    pl: {
        common: commonTranslations.pl,
        hexle: hexleTranslations.pl,
    },
    ru: {
        common: commonTranslations.ru,
        hexle: hexleTranslations.ru,
    },
    pt: {
        common: commonTranslations.pt,
        hexle: hexleTranslations.pt,
    },
    la: {
        common: commonTranslations.la,
        hexle: hexleTranslations.la,
    },
};

interface LanguageContextType {
    gameLang: GameLanguage;
    setGameLang: (lang: GameLanguage) => void;
    t: {
        common: typeof commonTranslations["es"];
        hexle: typeof hexleTranslations["es"];
    };
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode; }) {
    const [gameLang, setGameLangState] = useState<GameLanguage>("es");

    useEffect(() => {
        const savedLang = localStorage.getItem("juegitos-lang") as GameLanguage;
        if (savedLang && allTranslations[savedLang]) {
            // eslint-disable-next-line react-hooks/set-state-in-effect
            setGameLangState(savedLang);
        }
    }, []);

    const setGameLang = (lang: GameLanguage) => {
        setGameLangState(lang);
        localStorage.setItem("juegitos-lang", lang);
    };

    const t = allTranslations[gameLang];

    return (
        <LanguageContext.Provider value={{ gameLang, setGameLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
